# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/Nimorak

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/Nimorak

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Nimorak/CMakeFiles /data/Nimorak//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Nimorak/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nimorak

# Build rule for target.
nimorak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nimorak
.PHONY : nimorak

# fast build rule for target.
nimorak/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/build
.PHONY : nimorak/fast

src/board/attack.o: src/board/attack.c.o
.PHONY : src/board/attack.o

# target to build an object file
src/board/attack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/attack.c.o
.PHONY : src/board/attack.c.o

src/board/attack.i: src/board/attack.c.i
.PHONY : src/board/attack.i

# target to preprocess a source file
src/board/attack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/attack.c.i
.PHONY : src/board/attack.c.i

src/board/attack.s: src/board/attack.c.s
.PHONY : src/board/attack.s

# target to generate assembly for a file
src/board/attack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/attack.c.s
.PHONY : src/board/attack.c.s

src/board/board.o: src/board/board.c.o
.PHONY : src/board/board.o

# target to build an object file
src/board/board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/board.c.o
.PHONY : src/board/board.c.o

src/board/board.i: src/board/board.c.i
.PHONY : src/board/board.i

# target to preprocess a source file
src/board/board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/board.c.i
.PHONY : src/board/board.c.i

src/board/board.s: src/board/board.c.s
.PHONY : src/board/board.s

# target to generate assembly for a file
src/board/board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/board.c.s
.PHONY : src/board/board.c.s

src/board/movegen.o: src/board/movegen.c.o
.PHONY : src/board/movegen.o

# target to build an object file
src/board/movegen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/movegen.c.o
.PHONY : src/board/movegen.c.o

src/board/movegen.i: src/board/movegen.c.i
.PHONY : src/board/movegen.i

# target to preprocess a source file
src/board/movegen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/movegen.c.i
.PHONY : src/board/movegen.c.i

src/board/movegen.s: src/board/movegen.c.s
.PHONY : src/board/movegen.s

# target to generate assembly for a file
src/board/movegen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/board/movegen.c.s
.PHONY : src/board/movegen.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/main.c.s
.PHONY : src/main.c.s

src/nimorak/nimorak.o: src/nimorak/nimorak.c.o
.PHONY : src/nimorak/nimorak.o

# target to build an object file
src/nimorak/nimorak.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/nimorak/nimorak.c.o
.PHONY : src/nimorak/nimorak.c.o

src/nimorak/nimorak.i: src/nimorak/nimorak.c.i
.PHONY : src/nimorak/nimorak.i

# target to preprocess a source file
src/nimorak/nimorak.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/nimorak/nimorak.c.i
.PHONY : src/nimorak/nimorak.c.i

src/nimorak/nimorak.s: src/nimorak/nimorak.c.s
.PHONY : src/nimorak/nimorak.s

# target to generate assembly for a file
src/nimorak/nimorak.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/nimorak/nimorak.c.s
.PHONY : src/nimorak/nimorak.c.s

src/search/eval.o: src/search/eval.c.o
.PHONY : src/search/eval.o

# target to build an object file
src/search/eval.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/eval.c.o
.PHONY : src/search/eval.c.o

src/search/eval.i: src/search/eval.c.i
.PHONY : src/search/eval.i

# target to preprocess a source file
src/search/eval.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/eval.c.i
.PHONY : src/search/eval.c.i

src/search/eval.s: src/search/eval.c.s
.PHONY : src/search/eval.s

# target to generate assembly for a file
src/search/eval.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/eval.c.s
.PHONY : src/search/eval.c.s

src/search/perft.o: src/search/perft.c.o
.PHONY : src/search/perft.o

# target to build an object file
src/search/perft.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/perft.c.o
.PHONY : src/search/perft.c.o

src/search/perft.i: src/search/perft.c.i
.PHONY : src/search/perft.i

# target to preprocess a source file
src/search/perft.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/perft.c.i
.PHONY : src/search/perft.c.i

src/search/perft.s: src/search/perft.c.s
.PHONY : src/search/perft.s

# target to generate assembly for a file
src/search/perft.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/perft.c.s
.PHONY : src/search/perft.c.s

src/search/search.o: src/search/search.c.o
.PHONY : src/search/search.o

# target to build an object file
src/search/search.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/search.c.o
.PHONY : src/search/search.c.o

src/search/search.i: src/search/search.c.i
.PHONY : src/search/search.i

# target to preprocess a source file
src/search/search.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/search.c.i
.PHONY : src/search/search.c.i

src/search/search.s: src/search/search.c.s
.PHONY : src/search/search.s

# target to generate assembly for a file
src/search/search.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/search/search.c.s
.PHONY : src/search/search.c.s

src/table/repetition.o: src/table/repetition.c.o
.PHONY : src/table/repetition.o

# target to build an object file
src/table/repetition.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/repetition.c.o
.PHONY : src/table/repetition.c.o

src/table/repetition.i: src/table/repetition.c.i
.PHONY : src/table/repetition.i

# target to preprocess a source file
src/table/repetition.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/repetition.c.i
.PHONY : src/table/repetition.c.i

src/table/repetition.s: src/table/repetition.c.s
.PHONY : src/table/repetition.s

# target to generate assembly for a file
src/table/repetition.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/repetition.c.s
.PHONY : src/table/repetition.c.s

src/table/table.o: src/table/table.c.o
.PHONY : src/table/table.o

# target to build an object file
src/table/table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/table.c.o
.PHONY : src/table/table.c.o

src/table/table.i: src/table/table.c.i
.PHONY : src/table/table.i

# target to preprocess a source file
src/table/table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/table.c.i
.PHONY : src/table/table.c.i

src/table/table.s: src/table/table.c.s
.PHONY : src/table/table.s

# target to generate assembly for a file
src/table/table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/table.c.s
.PHONY : src/table/table.c.s

src/table/transposition.o: src/table/transposition.c.o
.PHONY : src/table/transposition.o

# target to build an object file
src/table/transposition.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/transposition.c.o
.PHONY : src/table/transposition.c.o

src/table/transposition.i: src/table/transposition.c.i
.PHONY : src/table/transposition.i

# target to preprocess a source file
src/table/transposition.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/transposition.c.i
.PHONY : src/table/transposition.c.i

src/table/transposition.s: src/table/transposition.c.s
.PHONY : src/table/transposition.s

# target to generate assembly for a file
src/table/transposition.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/transposition.c.s
.PHONY : src/table/transposition.c.s

src/table/zobrist.o: src/table/zobrist.c.o
.PHONY : src/table/zobrist.o

# target to build an object file
src/table/zobrist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/zobrist.c.o
.PHONY : src/table/zobrist.c.o

src/table/zobrist.i: src/table/zobrist.c.i
.PHONY : src/table/zobrist.i

# target to preprocess a source file
src/table/zobrist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/zobrist.c.i
.PHONY : src/table/zobrist.c.i

src/table/zobrist.s: src/table/zobrist.c.s
.PHONY : src/table/zobrist.s

# target to generate assembly for a file
src/table/zobrist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nimorak.dir/build.make CMakeFiles/nimorak.dir/src/table/zobrist.c.s
.PHONY : src/table/zobrist.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nimorak"
	@echo "... src/board/attack.o"
	@echo "... src/board/attack.i"
	@echo "... src/board/attack.s"
	@echo "... src/board/board.o"
	@echo "... src/board/board.i"
	@echo "... src/board/board.s"
	@echo "... src/board/movegen.o"
	@echo "... src/board/movegen.i"
	@echo "... src/board/movegen.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nimorak/nimorak.o"
	@echo "... src/nimorak/nimorak.i"
	@echo "... src/nimorak/nimorak.s"
	@echo "... src/search/eval.o"
	@echo "... src/search/eval.i"
	@echo "... src/search/eval.s"
	@echo "... src/search/perft.o"
	@echo "... src/search/perft.i"
	@echo "... src/search/perft.s"
	@echo "... src/search/search.o"
	@echo "... src/search/search.i"
	@echo "... src/search/search.s"
	@echo "... src/table/repetition.o"
	@echo "... src/table/repetition.i"
	@echo "... src/table/repetition.s"
	@echo "... src/table/table.o"
	@echo "... src/table/table.i"
	@echo "... src/table/table.s"
	@echo "... src/table/transposition.o"
	@echo "... src/table/transposition.i"
	@echo "... src/table/transposition.s"
	@echo "... src/table/zobrist.o"
	@echo "... src/table/zobrist.i"
	@echo "... src/table/zobrist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

